Tachyonite/Pawnmorpher

- 1.2/Defs/Aspects/Aspects_Misc.xml
Very simple change: Etherbroken (supposed to become numb) used to have a sapient limit of -0.2, while Etherbounded (accepting change, and less likely) used to have a sapient limit of -0.4.
Swaped the values. It has been requested many times in suggestions.
> Swap Etherbounded and Etherbroken values

- 1.2/Defs/Mutagens/defaultMutagen.xml
- Source/Pawnmorphs/Esoteria/MutagenDef.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/TfSys/Mutagen.cs
- Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs
- Source/Pawnmorphs/Esoteria/Utilities/GaussianRandom.cs
Instead of an Uniform distribution between 0.1 and 0.6 for sapiency when a pawn is transformed, here is a new formula based on a Gaussian distribution. For now we have:
- When mood is below 0.85 : N(mu = 0.6 * meanMutagenSapiencyDrop + 0.4 * unhapiness, sigma = stdMutagenSapiencyDrop)
- When mood is over 0.85 : linear relation with mood.
Mutagen values can be modified in the corresponding XML.
> New distribution for sapiency

- Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs
- Source/Pawnmorphs/Esoteria/Utilities/Cached.cs
As discussed on the Discord, Comp_MutationSeverityAdjust is responsible for a significant amount of lag when large numbers of pawns are involved.  Iron Wolf added some caching to improve performance, but there was still a noticeable amount of lag due to CompShouldRemove calling SeverityChangePerDay() every single tick.
This PR does two things:
1) Add a simple cache class to avoid copy-pasting the same caching code everywhere
2) Additionally cache the result of CompShouldRemove in addition to the values already cached.
This squashes pretty much the last of the performance problems related to Comp_MutationSeverityAdjust.  Tick speed is still noticably limited by HealthTracker ticks when large numbers of pawns exist on the map, but after these changes I don't believe this class is …
> Improve caching for Comp_MutationSeverityAdjust

- 1.2/Patches/Core_HumanHedifGraphics.xml
Followup to #313.
While testing my changes to reversion in that PR, I realized that during reversion, shrinking muzzles would now appear to pop back into fully-formed muzzles momentarily just before completely disappearing.  This is because muzzle graphics had no defined graphic for severity <0.1, so they pulled the default graphic instead.  I just added an additional invisible stage for severities between 0 and 0.1 for all muzzle graphics.  As far as I can tell, only muzzles have this issue so I left the other mutation graphics alone.
> Fix muzzle reversion graphics

- Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs
- Source/Pawnmorphs/Esoteria/Utilities/Cached.cs
Backports the performance fixes to Comp_MutationSeverityAdjust back to 1.2.
Also fixes some additional bugs that were identified:
- The presence/absence of the Reverter hediff is now properly cached as it was intended to be
- Mutations are only removed if a pawn has the Reverter hediff and severity is 0.  Previously, mutations would be removed if adjustment speed was negative (regardless of cause) the moment the first stage was reached, effectively skipping past said stage.
> Backport performance fixes to 1.2

- 1.3/Defs/Hediffs/Drugs.xml
- Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_EsotericRevert.cs
Previously, reversion serum started with only 0.5 severity, which meant fully-mutated morphs would not be reverted by a single serum.  I increased that to 1.0 severity, and additionally doubled the time it takes to dissipate so that even Paragon morphs will be fully reverted
> Reversion severity changes

- Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs
Makes reversion speed random with a skewed normal distribution.  The randomness is skewed so that on average mutations disappear slightly faster, but some stubborn mutations will last longer before being reverted.
Reversion speed follows this distribution currently (clamped between 0.81 and 1.3)
> Random reversion speed

- 1.3/Defs/Groups_Herd.xml
- 1.3/Defs/Groups_Pack.xml
- Defs/Thoughts/GroupThoughts/HerdThoughts.xml
- Defs/Thoughts/GroupThoughts/PackThoughts.xml
The morph-specific bedroom thoughts are currently so vague that I didn't realize they were even part of Pawnmorpher.  I had a bunch of lonely pawns who were upset at sleeping by themselves for no obvious reason, and I didn't figure it out until by chance I happened to read the one stage that mentions a pack.
Similarly, the pack and herd thoughts had vague names that overlapped with other thoughts.  The descriptions for those were fine, but it was odd to open up the thought screen and see a pawn with two different "Comfortable" thoughts.
This PR fixes all of that.  Pack- and Herd-based bedroom thoughts now always mention "pack" or "herd" in the description, and make it clear that the pawn is unhappy/less happy because they'd rather be sleeping with pack/herdmates.  Likewise, the barracks …
> Clarify morph-specific thoughts

- 1.3/Defs/Groups_Herd.xml
- 1.3/Defs/Groups_Pack.xml
- Defs/Thoughts/GroupThoughts/HerdThoughts.xml
- Defs/Thoughts/GroupThoughts/PackThoughts.xml
- Source/Pawnmorphs/Esoteria/HPatches/ToilsLayDownPatches.cs
- Source/Pawnmorphs/Esoteria/MorphGroupDef.cs
- Source/Pawnmorphs/Esoteria/MorphUtilities.cs
Note:  This PR also includes all of #327, so review this after that one merges
This is a bugfix and feature bundled together.  When testing #327, I realized that the "dull" and "mediocre" thought levels for bedrooms weren't showing up for pack- and herd-minded morphs.  After digging through the code, I determined this was because of the way the thought patch works.  Currently, it checks for a vanilla bedroom thought and then replaces it with the modified one.  However, the vanilla bedroom thought doesn't have a level for dull or mediocre, and so no thought exists to replace.
This PR changes the patch to instead delete the vanilla thoughts and replicate the vanilla logic but using the modified thoughtdefs.  In addition, I added a new feature while I was here.  Ascetic pack-minded morphs, …
> Ascetic bedroom thoughts

- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/Utilities/Collections/Checklist.cs
- Source/Pawnmorphs/Esoteria/Utilities/Collections/MultiDict.cs
- Source/Pawnmorphs/Esoteria/Utilities/RandUtilities.cs
Adds a pair of collections, which are used in the Hediff refactor.  Broke out into its own PR because the refactor is getting huge
MultiDict is a simple implementation of a multi-value dictionary
Checklist is a List and Iterator bundled together in a way that can be saved and loaded, which allows it to support interruptible iteration
Also added a RandRound utility method that probabilistic rounds a float up or down based on how close it is to either direction.
> New collections (Dev work)

- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_Descriptive.cs
- Source/Pawnmorphs/Esoteria/Hediffs/IMutagenicHediff.cs
- Source/Pawnmorphs/Esoteria/Hediffs/IMutationHediff.cs
- Source/Pawnmorphs/Esoteria/Hediffs/TransformationBase.cs
- Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_CompleteTF.cs
- Source/Pawnmorphs/Esoteria/MorphUtilities.cs
- Source/Pawnmorphs/Esoteria/MutationRules/Worker_MorphHediff.cs
- Source/Pawnmorphs/Esoteria/MutationTracker.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/Utilities/Collections/Checklist.cs
- Source/Pawnmorphs/Esoteria/Utilities/Collections/MultiDict.cs
IMutagenicHediff should now work as a stand-in for all mutagenic hediffs, decoupling everything from TransformationBase.
Also added a Hediff_Descriptive class that implements IDescriptiveHediff, and some bugfixes/tweaks to the collection classes
> Add an IMutagenicHediff interface (Hediff Refactor)

- 1.3/Defs/Interactions/AnimalNoises_GoatBleat.xml
- Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_StageChanges.cs
- Source/Pawnmorphs/Esoteria/Hediffs/IStageChangeObserverComp.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/Utilities/Cached.cs
Performance updates
- Added an abstract Hediff_StageChanges and IStageChangeObserverComp to handle hediffs and hediffcomps that do things on stage changes.
- Updated Hediff_AddedMutation to inherit from Hediff_StageChanges, and Comp_MutationSeverityAdjust to implement IStageChangeObserverComp.
- Comp_MutationSeverityAdjust lets the hediff notify it of stage changes rather than checking itself (CurStageIndex is too expensive to run multiple times every tick)
- Comp_MutationSeverityAdjust no longer inherits from Comp_SeverityPerDay, and instead replicates the small amount of logic it was using to cut down on overhead (e.g. multiple redundant IsHashTick calls).
- Comp_MutationSeverityAdjust no longer adjusts tick time based on whether the pawn is spawned or not.  It turns out this an …
> Performance updates

- Source/Pawnmorphs/Esoteria/ThingComps/SapienceTracker.cs
Updated former human check in MakePermanentlyFeral to take .IsFormerHuman on SapienceState into account.
closes #378
> Fixed SapienceTracker not checking new IsFormerHuman in MakePermanent

- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Utility/BodyMutationManager.cs
A proposed solution for the mutation bias described in issue #371.
By adding an increasing chance of completely skipping a body part with fewer available mutations.
The current percentage equates to just having an additional mutation option of "none".
This means that you are not guaranteed to mutate every single body part, and you are not guaranteed to get a production mutation with a completely random mutation source.
This is only wanted for complete random because that allows every mutation on every body part. For any targeted or limited mutation source, you will have much fewer available mutations and with a specific injector, you only have single choices available.
Right now I check if it is MutTypes_All, but it might be more correct to have it as an exposed option in XML defs as an …
> Potential fix for random mutation bias

- Schemas/MutationDef.xsd
- Source/Pawnmorphs/Esoteria/Hediffs/MutationDef.cs
- Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs
- Source/Pawnmorphs/Esoteria/MutationStagePatch.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
This will allow modifying mutation stages after a mutation has been compiled and objectified into the game. 
Which makes it possible to share stages between multiple derived mutation definitions with only small changes on each like graphics.
I tried to make key on MutationStage an attribute but then it didn't get deserialized properly, so I had to make it an optional element.
> MutationStage patching functionality

- 1.3/Defs/Chaocreatures/Chaothrumbo.xml
**Details**
Added the missing modExstension to Chaothrumbo xml to make the code see it as a proper chao-creature.
closes #387
> Fixed missing ChaomorphExstension in chaothrumbo xml.

- Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs
**Details**
Added missing patches to allow the manhunter targeting to see roaming morphs as threats and vice versa.
closes #380
> Fix for cowmorphs not being attacked by manhunter

- Source/Pawnmorphs/Esoteria/BodyUtilities.cs
- Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
Fixed issue by changing the way hediffs transfer identifies equivalent body parts for pawn <=> animal transition.
Instead of going by bodypartrecord address and matching each layer, it instead gets all body parts of identical definition (like all legs) and then matches for identical label (only 'right' leg).
This does mean however that if the target shape does not have an identical limb ("Right rear leg" vs "right leg") the hediff will still be lost in animal shape.
closes #427
> Issue427 transfer hediff

- Source/Pawnmorphs/Esoteria/HPatches/DoorPatches.cs
Changed door patch to only block pathing through doors of a hostile faction.
closes #429
> Former humans cannot pass through neutral or allied doors.

- Source/Pawnmorphs/Esoteria/TfSys/MergeMutagen.cs
Removed code that adds broken thoughts to reverted meld pawns.
Currently, regular reversion doesn't apply reversion thoughts, and the thoughts seem unfinished.
closes #405
> Issue405 - broken meld reverted thoughts

- Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
- Source/Pawnmorphs/Esoteria/TfSys/MergeMutagen.cs
- Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs
Calculates how much the pawn aged relative to life-span while transformed and adds that on reversion.
Also fixed rare issue with reversion where a relationship might not have a def, encountered while testing.
closes #438
> Issue438 - Incorrect reverted age

- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
Fixed exception caused by trying to set power state under ExposeData.
Made glow changing more responsible by avoiding the UpdateLit function, which saves a lot of calls to PowerOn.
closes #414
> Issue 414 - chamber init exception

- Schemas/MutationDef.xsd
- Source/Pawnmorphs/Esoteria/BodyUtilities.cs
- Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs
Added property on MutationStage to add a bodypart hitpoint multiplier across all body parts.
This allows to potentially moving some of the tankiness from powerful morphs into a mutation that can be added to other morphs with chamber later.
> Added globalHealthMultiplier to MutationStage

- 1.3/Defs/MutagenChamberNew.xml
- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
- Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs
Added Chaothrumbo as a species always available in chamber. 
Added optional filter to AnimalSelectorComp for custom filters on what should and shouldn't be selectable.
Chaothrumbo is now immediately selectable once you have an unstable genome available.
closes #445
> Issue 445 Unselectable chaothrumbo

- Source/Pawnmorphs/Esoteria/Work/Giver_TransformPrisoner.cs
The issue was that the job giver didn't check if the target could be reserved meaning that it'd give the job automatically even when something else had reserved the target, and then immediately fail.
Also, HasJobOnThing automatically calls JobOnThing in the base class if not overridden, so no reason to have duplicated code.
closes #424
> Issue 424 - Transform prisoner reservation error

- 1.3/Defs/Drugs/Drugs_Reverter.xml
- 1.3/Defs/Recipes/Surgeries.xml
- Source/Pawnmorphs/Esoteria/Recipes/PMRecipeDefGenerator.cs
Changed reverters to use IngestionOutcomeDoer_GiveHediff and included that in administer recipe generation.
Tested for duplicate administer recipes with seedpods and pills, but they are all considered Drugs and so not included.
MechaniteSlurry is still being included through GiveHediff.
Enabled hiding Halt and Adaptive cream operations if the ingredient is not available. That should make the list a lot shorter for morphs if you don't have some of them.
closes #462
> Issue 462 - No reverter operation.

- Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs
Split tag all mutations debug action into "Tag All mutations" and "Tag all genome mutations" as the original was.
closes #465
> Issue 465 - Tag all mutations

- 1.3/Defs/Chaocreatures/Chaothrumbo.xml
- 1.3/Defs/Things/Injectors.xml
- Source/Pawnmorphs/Esoteria/Chambers/AnimalGenomeStorageComp.cs
- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
- Source/Pawnmorphs/Esoteria/DefExtensions/AnimalSelectorOverrides.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs
Added a new extension to add an extendable way to modify how a PawnKind should appear in species selector.
Updated Unstable genome description.
Added selection reset method on SelectorComp.
Added special fail reason to unstable genome to allow hiding Chaothrumbo name.
> Chao thrumbo chamber polishing

- Source/Pawnmorphs/Esoteria/Chambers/ChamberDatabase.cs
- Source/Pawnmorphs/Esoteria/ThingComps/DatabaseStorage.cs
Changed inactive capacity to be subtracted from Free capacity
Databank will now immediately increase total storage without increasing free storage, which will then happen once it's powered.
closes #471
Empty database with 1 powered and 1 unpowered databank.
> Issue 471 - Databank power

- 1.3/Defs/Morphs/Animal/Animal_Parts.xml
- 1.3/Defs/Morphs/Animal/Avian/Avian_Parts.xml
- 1.3/Defs/Morphs/Animal/Avian/Ratite/Cassowary/Cassowary_Parts.xml
- 1.3/Defs/Morphs/Animal/Avian/Ratite/Emu/Emu_Parts.xml
- 1.3/Defs/Morphs/Animal/Avian/Ratite/Ostrich/Ostrich_Parts.xml
- 1.3/Defs/Morphs/Animal/Avian/Ratite/Ratite_Parts.xml
- 1.3/Defs/Mutations/AbstractMutations.xml
- 1.3/Patches/Core_HumanHedifGraphics.xml
- Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
Updated graphics processing to use mutation graphics if no <graphics> element is defined on stage.
If the mutation has an anchor defined that current stage *with* graphics element does not, then it assigns None texture to hide it.
Added generic ear hole and avian inherited.
Finished Ratite.
> Refactoring morph balance - Ratite

- Source/Pawnmorphs/Esoteria/ThingComps/SapienceTracker.cs
Making a pawn permanently feral will now remove sapience state which also removes the sapience need. It is now no longer possible to increase or decrease sapience with debug tools or pills.
closes #379
> Issue #379 - Restore sapience to permanently feral.

- Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs
Changed transformations to make be dropped first if carried by another pawn.
closes #486
> Issue 486 - Added check if pawn is carried before TF

- 1.3/Defs/Morphs/Animal/PawFooted/Carnivora/Canid/Lupine/Arctic Wolf/ArcticWolf_Parts.xml
- 1.3/Defs/Morphs/Animal/PawFooted/Carnivora/Vulpine/Arctic Fox/ArcticFox_Parts.xml
- 1.3/Defs/Morphs/Animal/PawFooted/Leporid/Snowhare/Snowhare_Parts.xml
- 1.3/Defs/Morphs/Animal/PawFooted/Ursine/Polar Bear/PolarBear_Parts.xml
- 1.3/Defs/Mutations/SkinMutations.xml
- Schemas/MutationDef.xsd
- Source/Pawnmorphs/Esoteria/AnimalClassDef.cs
- Source/Pawnmorphs/Esoteria/AnimalClassUtilities.cs
- Source/Pawnmorphs/Esoteria/DebugUtils/DebugLogUtils.MutationLogging.cs
- Source/Pawnmorphs/Esoteria/DebugUtils/DebugLogUtils.cs
- Source/Pawnmorphs/Esoteria/DebugUtils/DebugMenu_AddMutations.cs
- Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Giver_MutationChaotic.cs
- Source/Pawnmorphs/Esoteria/Hediffs/MutationDef.cs
- Source/Pawnmorphs/Esoteria/Hediffs/MutationRetrievers/Morph.cs
- Source/Pawnmorphs/Esoteria/MorphCategoryDef.cs
- Source/Pawnmorphs/Esoteria/MorphDef.cs
- Source/Pawnmorphs/Esoteria/MorphUtilities.cs
- Source/Pawnmorphs/Esoteria/MutationUtilities.cs
- Source/Pawnmorphs/Esoteria/PreceptComps/VeneratedMutation.cs
- Source/Pawnmorphs/Esoteria/User Interface/Dialog_PartPicker.cs
Change proposal to allow multiple class influences on mutations for shared mutations.
MutationDef now supports defining "classInfluence" or "classInfluences" in XML, and a new property "ClassInfluences" provide the total list regardless of how it has been added in the def.
The influence calculation now sorts mutations by number of influences to calculate singular first and then for those with more than 1 class, it finds the first class already existing and is counted as that.
There is some "issue" right now that if you have "Ursine" then arctic fur won't be counted as "Polar Bear" because it doesn't check inheritance tree. As soon as some other "Polar Bear" mutation is added, then both the Ursine and Arctic Fur would be counted as that as well, so I don't know how big the issue actually …
> Allow multiple ClassInfluences in MutationDef

- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
- Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs
Moved gizmo initialization on SpeciesSelector to ensure it's always available.
Added null check in case pawn inside the chamber has no graphics comp.
closes #495
> Issue 495 - muta-chamber error

- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
Fixed exception when chamber tries to spawn 0 morph silk.
Fixed off by one exception when transforming in chamber.
closes #497
> Issue 497 - Chamber morphsilk exception

- Source/Pawnmorphs/Esoteria/User Interface/Dialog_PartPicker.cs
QoL changes and fixes for PartPicker
1. Skin now changes color to the skin override of morph species most associated with currently selected mutations.
2. Removed random texture in background. (Presumably corner of map itself, fixed by moving entire preview rendering to -10x)
3. Hidden detail button if the mutation has no severity prop.
4. Removed species text from selected mutations to prevent text clipping on buttons.
5. Fixed head mutations not being aligned to head.
6. Fixed mutation details not showing correct mutation stage on changing severity.
Still need to figure out how to handle hair.
> Part picker polish

- 1.3/Defs/MutagenChamberNew.xml
- 1.3/Defs/Things/Buildings.xml
- 1.3/Defs/Things/TFWeapons.xml
- Languages/English/Keyed/Chambers.xml
- Languages/English/Keyed/UI_Localization.xml
- Languages/English/Keyed/Weapons.xml
- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
- Source/Pawnmorphs/Esoteria/ThingComps/AnimalSelectorComp.cs
Added label and description to AnimalSelectorCompProperties xml in chamber and mutagun.
AnimalSelectorComp now uses label and description defined in properties.
Added Weapons LanguageData file.
Added labels and descriptions for chamber and mutagun.
closes  #494
> Fix #494 Species selector on Mutation Chamber has no description.

- 1.3/Defs/StatDefs/Utils.xml
- Source/Pawnmorphs/Esoteria/HPatches/PawnPatches.cs
- Source/Pawnmorphs/Esoteria/PMStatDefOf.cs
Renamed it to Altered body size.
"Mutations have caused this pawn to change size."
> Added PM_BodySize stat to allow mutations to alter body size.

- Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs
- Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
- Source/Pawnmorphs/Esoteria/ThingComps/AlwaysMergedPawn.cs
Fixed blank melds lacking both skills and background by moving skill transfer to after meld is initialized as former human.
closes #475
> Issue 475 - blank melds

- Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs
Removed check and dependency on a component that does not exist on pawns that start as non-human.
> Fixed exceptions when reverting linked race.

- Languages/English/Keyed/FormerHumanNotifs.xml
- Source/Pawnmorphs/Esoteria/Hediffs/FormerHuman.cs
- Source/Pawnmorphs/Esoteria/Need_Control.cs
- Source/Pawnmorphs/Esoteria/SapienceStates/Animalistic.cs
- Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs
- Source/Pawnmorphs/Esoteria/ThingComps/SapienceTracker.cs
Fixed wrong letterbox appearing when the sapience level is increasing.
Special messages when the sapience level is increasing can now be used.
closes https://github.com/Tachyonite/Pawnmorpher/issues/517
> Issue 517 - Incorrect notification message with intelli-boost

- Source/Pawnmorphs/Esoteria/MutationUtilities.cs
Should be enough. Perhaps the whole last check (checking is the influence is not null) is not mandatory. To check.
Useful for morph balance.
> Class influence warning no longer appears when animal influence.

- Source/Pawnmorphs/Esoteria/MorphUtilities.cs
I don't know if this is the best approach. We access the DefDatabase<MorphDef> directly from multiple places, so just excluding the morphdef with errors (like missing Race) from the initialization code will not only have to be done in multiple places, but it'd then also have the mod throw errors in random other locations where it tries to access that information.
Modifying and excluding the morphdefs from the DefDatabase itself was the only guaranteed way to cover everything.
> Issue 527 - Invalid morphdef breaks mod initialization.

- Source/Pawnmorphs/Esoteria/HediffComp_Production.cs
Fixed issue related to the optimizations in production comps where it didn't calculate initial stage.
closes #555
> Issue 555 - Mutation tab breaks for newly added production mutations

- 1.3/Mods/Martens/Defs/Races.xml
Removed inheritance from lifeStageAges to avoid duplication errors due to the parent already having this node.
closes #560
> Duplication error from inheritance.

- 1.3/Defs/Factions/FactionDefs.xml
From the issue #514, the very first clue is this 
```
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
at RimWorld.Page_ChooseIdeoPreset+<>c.<PostOpen>b__25_0 (RimWorld.CultureDef x) [0x0000a] in <99518a644a3e4a7ea3fde566568df84a>:0 
at System.Linq.Enumerable+WhereListIterator`1[TSource].ToList () [0x00017] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
at Verse.GenCollection.TryRandomElement[T] (System.Collections.Generic.IEnumerable`1[T] source, T& result) [0x00029] in <99518a644a3e4a7ea3fde566568df84a>:0 
at RimWorld.Page_ChooseIdeoPreset.PostOpen () [0x0004c] in …
```
> Add missing `allowedCultures` to Free Morphs

- Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
Closes #576
Maybe we should look into how it should work. 
I assume the reason for this code is to remove all existing mutations and then add them back to allow progressing from 0.
The issue now is that the pawn is put into stasis, and only 1 mutation is ticked at a time. And so if you only changed the severity of an existing mutation that then didn't get removed until pawn leaves chamber.
A different part of the code goes "if mutation already exist on pawn (as in you only changed severity) it just un-halts.
But by setting all mutations to immediately be removed, you could feasibly put a pawn into the chamber, part pick a single mutation, and immediately eject the pawn to get a quick removal of all mutations.
It also means that adding a completely new mutation and setting it to severity 3 …
> Issue 576 - Fixed mutations vanishing on pawn exiting chamber.

- Source/Pawnmorphs/Esoteria/IncidentWorker/SheepChef.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/TransformerUtility.cs
- Source/Pawnmorphs/Esoteria/Utilities/PawnGeneratorUtility.cs
Calculates the minimum sheep age to equate to 17 years old when reverted, and ensures that the spawned animal is at least that.
Also fixed a rounding issue when calculating age on reversion. Sheep must be at least 2.55 years old to match 17, however it rounded to 2.0 which equates to 14.
Closes #542
> Issue 542 - Fixed Gordon missing a name part and age.

- Languages/English/Keyed/Settings.xml
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherSettings.cs
- Source/Pawnmorphs/Esoteria/User Interface/Dialog_Popup.cs
- Source/Pawnmorphs/Esoteria/User Interface/Settings/Dialog_VisibleRaceSelection.cs
- Source/Pawnmorphs/Esoteria/User Interface/Settings/VisibleRaceSelection.cs
Added a settings configuration to allow players to select what third-party (mutatable!) races to be patched as if they were human.
The selection list excludes human, explicit morphs and incompatible races.
> Allow users to enable mutation visuals on specific races.

- Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
Only show these warnings in debug mode, that way we don't have to repeatedly tell concerned users to ignore them.
We also don't want to throw warnings for integrating mods doing explicit injectors for end users.
> Hide debug warnings

- Source/Pawnmorphs/Esoteria/HPatches/RecipeDefPatch.cs
- Source/Pawnmorphs/Esoteria/ITabs/InjectorBills.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
This allows the tagging requirement to be effective even if the entire UI is replaced.
> Issue 550 - Replaced tagged restriction filter for injectors to HarmonyPatch

- 1.3/Defs/Morphs/Animal/Reptile/Lacertilia/Iguana/Iguana_Parts.xml
- 1.3/Defs/Morphs/Animal/Reptile/Ophidia/Cobra/Cobra_Parts.xml
- 1.3/Defs/StyleDefs/BeardDefs.xml
- 1.3/Defs/StyleDefs/HairDefs.xml
- 1.3/Patches/Core_HumanHedifGraphics.xml
- Source/Pawnmorphs/Esoteria/Graphics/InitialGraphics.cs
- Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
- Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs
- Source/Pawnmorphs/Esoteria/PMStyleDefOf.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/UserInterface/Dialog_PartPicker.cs
Mutations now remove beard if on Jaw or hair if on Head. Then reverts to initial when removed.
Moved iguana spikes and cobra hood to be Head-based mutations to replace hair.
Added support for blockedSites in part picker.
> Issue 681 - beard and hair

- 1.3/Defs/Things/TFWeapons.xml
- Source/Pawnmorphs/Esoteria/Hediffs/SyringeRifleTf.cs
Currently, Mutagun chooses the animal to transform the pawn into from a list of all animals. This can cause issues, as it may choose an animal that shouldn't ever be mutated into, such as a robot animal, or a(currently disabled) Dryad.
This patch changes the gun to choose from a list of normal former human animals. As a side effect, no Chaomorphs will appear out of the mutagun.
Also adjusted the Mutagun projectile and Tagging rifle projectile speeds from 15 to 50, which makes them not move at a slow motion pace
> Prevent mutagun from turning pawns into invalid former humans.

- Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs
Setting the animal's ideology to null just before destroying it. There may be side effects.
closes #487
> Issue 487 - Fix for revertion triggering funerals for former humans with ideology.

- Source/Pawnmorphs/Esoteria/Graphics/InitialGraphics.cs
- Source/Pawnmorphs/Esoteria/Thoughts/Worker_HasMutations.cs
Modified mutation thought worker to ignore mutations assigned to race by default.
Affects both body purists and Mutation Affinity. Neither will react to morph influence of their own base species.
This means that to satisfy a Mutation Affinity Orassan, you **have** to use non-"Cat" mutations.
Thoughtworker runs approx. once every 60 ticks. (once per second at x1 speed)
Closes #602
> Issue 602 - Body purist

- 1.3/Defs/Mutagens/defaultMutagen.xml
- 1.3/Defs/RulePacks/CoveringMutationLogPacks.xml
- 1.3/Defs/RulePacks/MutationPackBases.xml
- Source/Pawnmorphs/Esoteria/HediffGiver_Mutation.cs
- Source/Pawnmorphs/Esoteria/MutationCauseUtility.cs
- Source/Pawnmorphs/Esoteria/MutationCauses.cs
- Source/Pawnmorphs/Esoteria/MutationLogEntry.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Hid cause if the cause has no rules provided.
Renamed "label" to "label_text" because it got confused default "label" (name of hediff).
Renamed "mutagen" to "mutagen_cause" to match what is expected by old code and XML.
Closes #372
> Issue 372 - mutation log

- Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs
- Source/Pawnmorphs/Esoteria/Graphics/InitialGraphics.cs
- Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs
- Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_StageChanges.cs
- Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
Disabled core rimworld logic for mutation hediffs, as this type of hediffs never utilizes any of the underlying logic. Skipping it makes mutations significantly cheaper to maintain. (Stuff like hediffGivers, Vomiting, etc, is handled in core logic.)
Moved mutation abilities to mutation derived mutation type and moved all stage handling to the intermediate stage management type. (It was duplicated logic)
- Now the mutations are basically only occasionally checking if severity crossed stage threshold and then triggers an update reacting to that and then returns to being inert performance wise.
Significantly reduced overhead of scaling logic and should now support races with different base size.
Might still be an issue related to calling HAR "ResolveAllGraphics" way too often. As far as I …
> Optimizations and fixes for 1.4

- 1.4/Defs/MorphsAndMutationDefs/Shared/HandMutations.xml
A recent-ish changed reverted hand mutation manipulation penalties to use manipulation offsets instead of body part efficiency offsets.  This has some weird side effects, such as bird hands getting damaged causing the manipulation of the pawn's good hand to go down due to the manipulation-penalty-from-damage and manipulation offset stacking.
This PR just converts the manipulation penalties to the equivalent efficiency offsets instead.  Note that capacity penalties for hands is doubled since you have two of them, so the body part efficiency penalty must be twice as strong to have the same end result.
As a side note, I reduced the effective penalty for having two bird wing nubs from -100% to -90%.  Complete loss of manipulation was a bit too steep in my eyes, especially if a pawn was …
> Use part efficiency instead of manipulation offsets for hand mutations

- Source/Pawnmorphs/Esoteria/HPatches/BiosculpterPatches.cs
A simple patch to ensure biosculptors don't attempt to remove mutations during the bioregeneration cycle.  Compiled and tested successfully -- the pod was able to heal a brain scar, but it left the pawn's mutations alone.  Prior to this fix, ear mutations (and possibly eye mutations) would be removed by bioregeneration.
> Patch biosculptors to prevent bioregeneration from removing mutations

- Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs
Fixes #762 
Currently, this changes the scale patch to only scale based on the PM_BodySize stat.  In the future it would be preferable to add a mod toggle to swap between that and scaling based on (mod-added) sources of body size changes.
> Fix children scaling with the body size patch

- .github/workflows/Build_Test.yml
This makes use of a new feature in github tasks to name individual runs by selected branch.
https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name
See available github context variables:
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> Update workflow to name individual runs by branch.

- Source/Pawnmorphs/Esoteria/HPatches/GamePatches.cs
This patch was causing errors and missing heads when various race mods were installed.  The issue is that the patch was hitting any head with the word "narrow" in it (e.g. AG_SlugFace_Narrow), and a number of mods don't use the same naming scheme as vanilla so the replaced heads were null.
I could have just not replaced the head if the replacement def type didn't exist, but I figured we shouldn't be replacing alien heads anyway since they don't usually show PM mutations
> Limit head replacement to explicitly removed heads

- Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_StageChanges.cs
- Source/Pawnmorphs/Esoteria/Hediffs/MutationDef.cs
Mutation hediffs were being a bit slow again.  I went through and cleaned up a lot of the caching to minimize what's going in in `.Tick()` directly or indirectly.  It still chugs quite a bit if you have a ton of hediffs, but at the moment the bottleneck is now vanilla's HediffWithComps.PostTick() rather than anything we're doing.
Before:
After:
> Performance improvements

- Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs
- Source/Pawnmorphs/Esoteria/Utilities/StatsUtility.cs
- Source/Pawnmorphs/Esoteria/Utilities/TimedCache.cs
Paragon aspect did not work because stat cache in Ticker component did not get refreshed.
Seems PostTick method was not getting called?
Moved caches be time based instead of HashTick, and moved stats to use centralized StatsUtility cache.
The problem with IsHashIntervalTick is that it can only be used in a method guaranteed to run every tick, otherwise you may just so happen to never hit the exact tick that counts as hash tick for the pawn.
Now I just say that we can accept up to 300 ticks delay in responsiveness from gaining aspect. (5 seconds at 60tps)
StatsUtility returns null if not not cached and pawn isn't spawned because GetStatValue in that case errors. Coult potentially be changed to return StatDef.defaultBaseValue instead in those cases.
Fixes #774
> Issue 774 - paragon aspect not working

- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
The Krafs stubs were being preferred over the real Rimworld assembly, which made it annoying to examine Vanilla code (jumping to definitions would jump to the decompiled stubs instead of the real definition).  This changes it so that the stubs are only loaded if the real Rimworld assembly cannot be found.
> Conditionally load the Krafs stubs only if the real Rimworld dependencies are not available

- Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
- Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs
- Source/Pawnmorphs/Esoteria/TransformerUtility.cs
Fixes #751 for real this time
There was an unneeded minimum age in the race shift utilities that always made race-shifted pawns at least 17.  That was only meant to be used when generating former humans and doesn't make any sense for morph races (which could potentially have a lower max age than 17, among other things).
The age limit for generated former humans should probably be rethought now that biotech adds kids, but that can be saved for a future PR.
> Remove an unnecessary min-age limit from the race shifting utility

- Languages/English/Keyed/Settings.xml
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherSettings.cs
- Source/Pawnmorphs/Esoteria/UserInterface/FilterListBox.cs
- Source/Pawnmorphs/Esoteria/UserInterface/Settings/Dialog_BlacklistAnimal.cs
Added yet another options window to allow users to manually disable specific types of animals from being a potential result in a completely random transformation.
Does not require restart.
> Options to black list individual animals from being potential picks during full random transformations.

- Languages/English/Keyed/Settings.xml
- Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
- Source/Pawnmorphs/Esoteria/FormerHumans/FormerHumanRestrictions.cs
- Source/Pawnmorphs/Esoteria/Genebank/DatabaseUtilities.cs
- Source/Pawnmorphs/Esoteria/Need_Control.cs
- Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
- Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
- Source/Pawnmorphs/Esoteria/PawnmorpherSettings.cs
- Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs
- Source/Pawnmorphs/Esoteria/ThingComps/Comp_CanBeFormerHuman.cs
- Source/Pawnmorphs/Esoteria/UserInterface/Settings/Dialog_BlacklistAnimal.cs
- Source/Pawnmorphs/Esoteria/UserInterface/Settings/Dialog_RaceReplacements.cs
- Source/Pawnmorphs/Esoteria/Utilities/RandUtilities.cs
Reworked how former humans are decided and managed:
- Added a concept of restricted and banned former humans.
- Restricted former humans cannot happen in fully random mutagen.
- Banned former humans cannot happen at all.
- Centralized former human check.
- Added default former human ban list configuration.
- All animals associated with powerful morphs are by default restricted.
- Genetic Rim archotech centipede is by default disabled.
- Alpha animals gallatross is by default restricted.
- Added options menu to ban or restrict former humans.
- Animals related to defined morphs can be restricted but not banned.
- Added configurable chance for hostiles to retain their faction. (Also affects pawns from friendly factions)
- Default is off.
- Animals spawning as former humans now have a …
> Former human update

- Source/Pawnmorphs/Esoteria/HPatches/BedPatches.cs
Rewrote CanUseBedEver postfix to not circumvent vanilla bodysize bed restriction.
> Fix for pawns choosing to sleep in cribs.

- Patches/Core/Core_AddedComps.xml
- Source/Pawnmorphs/Esoteria/FormerHumans/FormerHumanPawnGenerator.cs
- Source/Pawnmorphs/Esoteria/TransformerUtility.cs
Closes #818
Ferian race mod did not use BasePawn and so didn't get a mutation tracker assigned causing lots of errors.
Changing the patch to point at any XML with "Pawn" as class should cover custom pawn definitions too.
> Issue 818 - Changed mutation tracker comp patch to assign to all pawns.

- Source/Pawnmorphs/Esoteria/Thoughts/FormerHumanMemory.cs
VanillaTraitsExpanded checks CurStageIndex in a gain thought prefix, which means the thought hasn't bee assigned to a pawn yet.
For former human memories, this will then check sapience level and cause a null reference.
Closes #694
Closes #418
> Issue 694 + 418 - error on gaining thought.

- Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs
simple fix to allow sapient former humans to carry things on caravans regardless if they are pack animals 
fixed #847
> allowed sapient former humans to carry things on caravans

- Source/Pawnmorphs/Esoteria/HPatches/HealthCardUtilsPatch.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_Descriptive.cs
- Source/Pawnmorphs/Esoteria/MutationRuleDef.cs
- Source/Pawnmorphs/Esoteria/MutationTracker.cs
Some optimizations to remove a no-longer-needed harmony patch for pawn health tab.
I noticed that Rimworld now allows you to override Hediff.Description, so we can now inject our custom descriptions into vanilla's tooltip system without using a custom patch!
Also an issue of MutationTracker calling CanInfect every single tick for every single pawn.
> Optimize mutation descriptions

- 1.4/Defs/Drugs/Drugs_Antigen.xml
- 1.4/Defs/Drugs/Drugs_Bases.xml
- 1.4/Defs/Drugs/Drugs_Pills.xml
- 1.4/Defs/Hediffs/Hediffs_Bases.xml
- 1.4/Defs/Hediffs/Hediffs_Drug.xml
- 1.4/Defs/Hediffs/Hediffs_Misc.xml
- 1.4/Defs/MorphsAndMutationDefs/Shared/GenericMutations.xml
- 1.4/Defs/Mutagens/ChaoticMutagens.xml
- 1.4/Defs/Mutagens/defaultMutagen.xml
- 1.4/Defs/RulePacks/MutationCauseRulePacks.xml
- 1.4/Defs/Things/Morph Products.xml
- Languages/English/Keyed/MutationLog.xml
- Source/Pawnmorphs/Esoteria/Hediffs/CompProperties_RemoveType.cs
- Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs
- Source/Pawnmorphs/Esoteria/Hediffs/SpreadingMutationComp.cs
- Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_GiveHediff.cs
- Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_GiveHediffAll.cs
- Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_GiveHediffIfNonePresent.cs
- Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_GiveHediffRandom.cs
- Source/Pawnmorphs/Esoteria/MutagenDef.cs
- Source/Pawnmorphs/Esoteria/MutagenicBuildupUtilities.cs
- Source/Pawnmorphs/Esoteria/MutationCauses.CauseEntry.cs
- Source/Pawnmorphs/Esoteria/MutationCauses.cs
- Source/Pawnmorphs/Esoteria/MutationLogEntry.cs
- Source/Pawnmorphs/Esoteria/PMRulePackDefOf.cs
- Source/Pawnmorphs/Esoteria/Things/InjectorGenerator.cs
- Source/Pawnmorphs/Esoteria/TransformerUtility.cs
Added mutation log cause support for milk + egg ingesting and spreading.
Added mutation log support for identifying injectors, ingestibles, and updating location on mutagenic buildup.
Migrated more hediffs to Mutagenic base from MorphTF.
> Mutation log extensions
