.gitignore
About/Manifest.xml
About/Version.xml
Defs/UpdateFeatures.xml
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorpherModBase.cs
Source/Pawnmorphs/Esoteria/packages.config
build.ps1

Add the HugsLib mod update message to the master branch, this would include making HugsLib a dependency

Add Update Message to Master

---

Defs/Morphs/Cat/Cat_Memories.xml
Defs/Morphs/Chicken/Chicken_Memories.xml

Catmorph and chookmorph change and reversion memories

---

README.md

yeah i just updated the readme.md
just added like 4 text characters
nothing big here

just a README.md update

---

Patches/Mod Addons/Addon_RemoteTech.xml

added research needs and fixed blinker offset
fixed mutation buildup severity per tick
nothing big here

updated Addon_RemoteTech,fixes and stuff

---

Patches/Core/Core_Textiles.xml
Source/Pawnmorphs/Esoteria/HPatches/GatherableBodyResourcePatch.cs
Source/Pawnmorphs/Esoteria/HediffComp_Production.cs
Source/Pawnmorphs/Esoteria/PMThingCategoryDefOf.cs

Wool (and other Textiles, I suppose, if there are any) maintains its color when sheared off unusually colored morphs/animals

colored production textiles

---

Source/Pawnmorphs/Esoteria/Graphics/MorphGraphicsUtils.cs
Source/Pawnmorphs/Esoteria/Hybrids/HybridRaceSettings.cs
Source/Pawnmorphs/Esoteria/Utilities/RandUtilities.cs

7:14 PM] Iron Wolf (Dev): I’ve made a new branch on github, graphics-rewrite,  for this with a rough outline of a system that I think would work better but they’re not really hooked up to anything. If you could take a look at it and start replacing the old morph skin/hair color code that’s be a big help

MorphGraphicsUtils rewrite

---

About/Manifest.xml
Defs/Mutagens/Bases.xml
Defs/Mutagens/defaultMutagen.xml
Examples/MutationDef.xml
Patches/Mod Addons/Addon_FixAndroidsTiers.xml
Schemas/MutationDef.xsd
Source/Pawnmorphs/Esoteria/DebugUtils/DebugLogUtils.MutationLogging.cs
Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs
Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs
Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/User Interface/Dialog_PartPicker.cs

- color aspects are rarer 
- fixed android tiers patch 
- removed afflicted and made paragon rarer (pending rebalancing)

Hot patch for 1.9

---

Source/Pawnmorphs/Esoteria/AnimalClassDefOf.cs
Source/Pawnmorphs/Esoteria/AspectDefOf.cs
Source/Pawnmorphs/Esoteria/Aspects/Coloration.cs
Source/Pawnmorphs/Esoteria/BackstoryDefOf.cs
Source/Pawnmorphs/Esoteria/BuildingDefOf.cs
Source/Pawnmorphs/Esoteria/Chambers/ChamberJobDefOf.cs
Source/Pawnmorphs/Esoteria/HPatches/PawnComponentPatches.cs
Source/Pawnmorphs/Esoteria/HairDefOf.cs
Source/Pawnmorphs/Esoteria/Hediffs/MorphTransformationDefOf.cs
Source/Pawnmorphs/Esoteria/Hybrids/HThoughtDefOf.cs
Source/Pawnmorphs/Esoteria/MorphDefOfs.cs
Source/Pawnmorphs/Esoteria/MorphGroupDefOf.cs
Source/Pawnmorphs/Esoteria/MutagenDefOf.cs
Source/Pawnmorphs/Esoteria/MutationsDefOf.cs
Source/Pawnmorphs/Esoteria/PMDesignationDefOf.cs
Source/Pawnmorphs/Esoteria/PMIncidentDefOf.cs
Source/Pawnmorphs/Esoteria/PMInteractionDefOf.cs
Source/Pawnmorphs/Esoteria/PMJobDefOf.cs
Source/Pawnmorphs/Esoteria/PMNeedDefOf.cs
Source/Pawnmorphs/Esoteria/PMRulePackDefOf.cs
Source/Pawnmorphs/Esoteria/PMStatDefOf.cs
Source/Pawnmorphs/Esoteria/PMThingDefOf.cs
Source/Pawnmorphs/Esoteria/PMThoughtDefOf.cs
Source/Pawnmorphs/Esoteria/PMTraitDefOf.cs
Source/Pawnmorphs/Esoteria/SapienceStateDefOf.cs
Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs
Source/Pawnmorphs/Esoteria/TfHediffDefOf.cs
Source/Pawnmorphs/Esoteria/TfRelationDefOf.cs
Source/Pawnmorphs/Esoteria/Thoughts/ThoughtDefOfs.cs

Reverts Tachyonite/Pawnmorpher#197
forget changes in dev got pulled into the hotfix branch 
reverting this pull

Revert "pull Hot fix changes into master"

---

Source/Pawnmorphs/Esoteria/AnimalClassDefOf.cs
Source/Pawnmorphs/Esoteria/AspectDefOf.cs
Source/Pawnmorphs/Esoteria/Aspects/Coloration.cs
Source/Pawnmorphs/Esoteria/BackstoryDefOf.cs
Source/Pawnmorphs/Esoteria/BuildingDefOf.cs
Source/Pawnmorphs/Esoteria/Chambers/ChamberJobDefOf.cs
Source/Pawnmorphs/Esoteria/HPatches/PawnComponentPatches.cs
Source/Pawnmorphs/Esoteria/HairDefOf.cs
Source/Pawnmorphs/Esoteria/Hediffs/MorphTransformationDefOf.cs
Source/Pawnmorphs/Esoteria/Hybrids/HThoughtDefOf.cs
Source/Pawnmorphs/Esoteria/MorphDefOfs.cs
Source/Pawnmorphs/Esoteria/MorphGroupDefOf.cs
Source/Pawnmorphs/Esoteria/MutagenDefOf.cs
Source/Pawnmorphs/Esoteria/MutationsDefOf.cs
Source/Pawnmorphs/Esoteria/PMDesignationDefOf.cs
Source/Pawnmorphs/Esoteria/PMIncidentDefOf.cs
Source/Pawnmorphs/Esoteria/PMInteractionDefOf.cs
Source/Pawnmorphs/Esoteria/PMJobDefOf.cs
Source/Pawnmorphs/Esoteria/PMNeedDefOf.cs
Source/Pawnmorphs/Esoteria/PMRulePackDefOf.cs
Source/Pawnmorphs/Esoteria/PMStatDefOf.cs
Source/Pawnmorphs/Esoteria/PMThingDefOf.cs
Source/Pawnmorphs/Esoteria/PMThoughtDefOf.cs
Source/Pawnmorphs/Esoteria/PMTraitDefOf.cs
Source/Pawnmorphs/Esoteria/SapienceStateDefOf.cs
Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs
Source/Pawnmorphs/Esoteria/TfHediffDefOf.cs
Source/Pawnmorphs/Esoteria/TfRelationDefOf.cs
Source/Pawnmorphs/Esoteria/Thoughts/ThoughtDefOfs.cs

Changes from dev are already added to the master branch , re adding changes done in hotfix

Re Adding changes from hotfix into master 

---

1.2/Defs/Things/Buildings.xml
Defs/Hediffs/Mutations/HandMutations.xml

Fixes feline hands not adapting and the Mutation Sequencer now works indoors
closes issues #275 and #276

Fixed feline hands not adapting and Mutation Sequencer now works indoors

---

1.2/Defs/WorkGivers.xml
1.2/Patches/Core/Core_FixHarmonizerThought.xml
1.2/Patches/Core_FixEmpireHostility.xml
1.2/Patches/Core_HumanHedifGraphics.xml
Defs/Hediffs/Hediffs_Diseases.xml
Source/Pawnmorphs/Esoteria/Chambers/GenomeDefGenerator.cs
Source/Pawnmorphs/Esoteria/DefExtensions/HarmonizerTransferWorker.cs
Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/GiddyUpPatch.cs
Source/Pawnmorphs/Esoteria/HPatches/ThingOwnerUtilityPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/ThoughtHandlerPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/WorkGiverPatches.cs
Source/Pawnmorphs/Esoteria/Jobs/Driver_UseMutationScanner.cs
Source/Pawnmorphs/Esoteria/MutationUtilities.cs
Source/Pawnmorphs/Esoteria/PMJobDefOf.cs
Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj.user
Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs
Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs
Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs
Source/Pawnmorphs/Esoteria/ThingComps/MutationSequencerComp.cs
Source/Pawnmorphs/Esoteria/Thoughts/IThoughtTransferWorker.cs
Source/Pawnmorphs/Esoteria/Utilities/LinqUtils.cs
Source/Pawnmorphs/Esoteria/Work/Giver_WorkAtSequencer.cs

Merge the latest patches into master

merge fixes in dev into master

---

1.3/Patches/Core_HumanHedifGraphics.xml
Source/Pawnmorphs/Esoteria/Hediffs/Comp_MutationSeverityAdjust.cs

Pulling in the additional fixes I made in #313 and #314 into 1.3 as well

1.3 Comp_MutationSeverityAdjust fixes

---

1.1/Defs/Hediffs/Hediffs_Bases.xml
1.2/Defs/Hediffs/Hediffs_Bases.xml
1.2/Defs/Morphs/Cobra/Cobra_Parts.xml
1.3/Defs/Morphs/Cobra/Cobra_Parts.xml
1.3/Defs/Morphs/Gazelle/Gazelle_Parts.xml
1.3/Defs/Morphs/Iguana/Iguana_Parts.xml
1.3/Patches/Core_HumanHedifGraphics.xml
Schemas/MutationDef.xsd
Source/Pawnmorphs/Esoteria/Graphics/MutationGraphicsData.cs
Source/Pawnmorphs/Esoteria/Graphics/TaggedBodyAddon.cs
Source/Pawnmorphs/Esoteria/Hediffs/MutationDef.cs
Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs

merge the new graphic injection system into the development build

merged the graphics injection system into dev 

---

1.2/Defs/Morphs/Chao/Chao_Full.xml
1.3/Defs/HistoryEventDefs/HistoryEventDefs.xml
1.3/Defs/Morphs/Chao/Chao_Full.xml
1.3/Mods/Ideology/Defs/Issues.xml
1.3/Mods/Ideology/Defs/Precepts_FormerHumans.xml
1.3/Mods/Ideology/Defs/Thoughts/FH_PreceptThoughts.xml
1.3/Mods/Ideology/Patches/AddPlantComps.xml
Schemas/PreceptDef.xsd
Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/HuntingPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/ThoughtHandlerPatches.cs
Source/Pawnmorphs/Esoteria/IFoodPreferenceAdjustor.cs
Source/Pawnmorphs/Esoteria/PMFoodUtilities.cs
Source/Pawnmorphs/Esoteria/PMHistoryEventDef.cs
Source/Pawnmorphs/Esoteria/PMIssueDefOf.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PreceptComps/FeralFoodAdjustor.cs
Source/Pawnmorphs/Esoteria/ThingComps/PlantIngesterListener.cs
Source/Pawnmorphs/Pawnmorph.sln.DotSettings

merge the new feral behavior precepts into dev now that the core functionality is working

Merge Feral behavior Precepts into dev for further testing

---

1.3/Defs/MutationBase.xml
Source/Pawnmorphs/Esoteria/DebugUtils/DebugLogUtils.Hediffs.cs
Source/Pawnmorphs/Esoteria/Hediffs/SpreadingMutationComp.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj

Added some hediff performance debugging tools, and optimized SpreadingMutationComp

Performance things

---

1.1/Defs/Hediffs/Hediffs_TF.xml
1.2/Defs/Hediffs/Hediffs_TF.xml
1.3/Defs/Hediffs/Hediffs_TF.xml
1.3/Defs/StatDefs/MutagenStats.xml
Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs
Source/Pawnmorphs/Esoteria/Hediffs/MutagenicPain.cs
Source/Pawnmorphs/Esoteria/PMStatDefOf.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj

merge the addition of the mutagen pain stat for further work in dev

merge the new pain stat into dev for further work

---

1.3/Defs/Things/Plants.xml
Source/Pawnmorphs/Esoteria/HPatches/ThingDefPatches.cs
Source/Pawnmorphs/Esoteria/Things/ExpandedPlant.cs

Fixed expanded plants so that they will properly grow in below-freezing temperatures (with respect to their growth temperature range).  Also made them respect light levels like other plants, and explicitly declared glowvines as not requiring light.
Note:  This doesn't fix the issue with sowing plants, so they still won't be sowed in winter

Plant stuff

---

1.3/Defs/Morphs/Cassowary/Cassowary_Parts.xml
1.3/Defs/Mutations/FootMutations.xml

This fixes a few typos in some of the foot mutations. Outside of the typos, it gives better descriptions for the avian feet so they are not just copies of the chicken feet.

Fixed typos in some of the foot mutations

---

1.3/Defs/Morphs/Capybara/Capybara_MorphDef.xml
1.3/Defs/Morphs/Dromedary/Dromedary_MorphDef.xml
1.3/Defs/Morphs/Fox/Fennec Fox/FennecFox_Memories.xml
1.3/Defs/Morphs/Gazelle/Gazelle_MorphDef.xml
1.3/Defs/Morphs/Ibex/Ibex_Parts.xml

Added capybaramorph morphdef

---

1.3/Defs/Morphs/Chinchilla/Chinchilla_Parts.xml

Added chinchilla part descriptions

Added chinchilla part descriptions

---

1.1/Defs/Morphs/AlphaBeaver/Alphabeaver_Full.xml
1.2/Defs/Morphs/AlphaBeaver/Alphabeaver_Full.xml
1.3/Defs/Morphs/AlphaBeaver/Alphabeaver_Full.xml
1.3/Mods/Ideology/Defs/Precepts_FormerHumans.xml

Typo corrections in alphabeaver and former human precept.

---

Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs

Reworked ForceTransformation to use new(?) transformation system and look for transforming stages on mutagenic hediff instead of IPawnTransformers.
Closing issues
closes #392

Fix for issue #392 'ForceTransformation'

---

1.3/Defs/Drugs/Drugs_Antigen.xml
1.3/Defs/Factions/FactionDefs.xml

**Details**
Added halt cream to Mutagen Lab.
Removed explicit assignment of traders from morph faction as it seems they are being added automatically.
closes #406 
closes #402

Minor xml adjustments.

---

1.3/Defs/Drugs/Drugs_TransformerSerums.xml
Source/Pawnmorphs/Esoteria/IngestionEffects/AddMorphCategoryTfHediff.cs

Fixed mutaserum, Powerful not working because all restricted animals were being excluded.
closes #409

Fixed #409: Mutaserum, Powerful not working.

---

1.3/Defs/Drugs/Drugs_MechaniteSlurry.xml
1.3/Defs/Morphs/Chao/Chao_Full.xml

Fixed chaomorph hediff not working.
Fixed self-injecting mutagenic slurry only working half the time.
closes #385

Fix for mutagenic slurry.

---

Source/Pawnmorphs/Esoteria/Aspect.cs

Changed aspects to calculate skill impact when added in addition to stage change, this should fix single-stage aspects not working.
closes #420

Aspects now calculate skill change also when added.

---

1.3/Defs/Things/Injectors.xml

Makes Unstable Genome forbiddable.
closes #423

Fixed for unstable genome not being forbiddable.

---

1.3/Defs/MutagenChamberNew.xml
Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
Source/Pawnmorphs/Esoteria/Jobs/Driver_TransformPrisoner.cs

**Details**
Fixed not being able to carry downed prisoner to muta chamber.
Fixed muta chamber not putting contained pawn into stasis.
closes #412

Transform prisoner action and stasis.

---

Languages/English/Keyed/Plants.xml
Source/Pawnmorphs/Esoteria/HPatches/ThingDefPatches.cs

Added optimal grow temperature range to glowvine description.
Added translation keys for optimal growth range.
closes #432

Issue #432 - Glowvines don't show optimal growth range.

---

Source/Pawnmorphs/Esoteria/HPatches/AnimalPenUtilityPatches.cs

Added transpiler patch for AnimalPenUtility.GetHitchingPostAnimalShouldBeTakenTo.
closes #419

Issue 419 - former human hitching

---

Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs
Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Fixed social thoughts not being copied over and updated reverse direction thoughts to aim at new pawn.
closes #448

Issue #448 - Fixed social relations not being visible for sapient former humans.

---

Languages/English/Keyed/Hediffs.xml
Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs

Updated race changed notification to say previous species label instead of always human.
closes #455

Issue 455 - Changed race notification

---

Defs/Hediffs/Hediffs_Misc.xml

Removed invalid tag from feral pill description.
closes #382

Issue 382 - Feral pill description

---

Source/Pawnmorphs/Esoteria/MergedPawnUtilities.cs

Disabled adding split mind for now.
closes #403

Issue 403 - Split mind.

---

Languages/English/Keyed/Bills.xml
Source/Pawnmorphs/Esoteria/IngredientValueGetter_Mutanite.cs

Added translation key to bills requiring raw mutanites.
closes #373

Issue 373 - Slurry bill description.

---

Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs

Issue 481 - Cobras

---

1.3/Defs/Things/Plants.xml

Corrected small typo in glowvine descriptions
closes #476

Issue 476 - Fixed glowvine typo.

---

Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs

Issue 498 - Incorrect label for friendly manhunter setting

---

Source/Pawnmorphs/Esoteria/HPatches/SelectorPatch.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj

Added new transpiler patch to allow multi-selecting sapients.
closes #479

Issue 479 - Multi-Select former humans with pawns.

---

Schemas/MutationDef.xsd
Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs

```
<verbOverrides>
<li>
<label>avian claws</label>
<power>5</power>
</li>
</verbOverrides>
```

Allow modifying verb in stages.

---

Schemas/MutationDef.xsd
Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs

Enables setting verb tool chanceFactor using VerbOverrides.

Added chanceFactor to verbOverrides.

---

1.3/Defs/Terrain/Mutagenics.xml

See Mutagenesis for a use with statues.
Mutanite is its own category, so it cannot be used (normally) for weapons and stone cutting. It should act quite like Jade.
We can make walls (but it's basically useless given the price, could think of some uses/modifications?).
Floors and all not added yet. See Mutagenesis for that (temples?).

Mutanite usable for stuff

---

1.3/Defs/Recipes/Silk.xml

Corrected typo in Hazsilk recipes.
closes #532

Issue 532 - Typo in hazsilk bills

---

1.3/Defs/Aspects/Aspects_Canid.xml
1.3/Defs/Aspects/Aspects_Coloration.xml
1.3/Defs/Aspects/Aspects_FormerHuman.xml
1.3/Defs/Aspects/Aspects_Merged.xml
1.3/Defs/Aspects/Aspects_Misc.xml
1.3/Defs/Aspects/Aspects_Prideful.xml
1.3/Defs/Aspects/Aspects_Production.xml
1.3/Defs/Morphs/Animal/PawFooted/Carnivora/Feline/Pantherine/Pantherine_MorphDef.xml
1.3/Defs/Traits.xml
Schemas/AspectDef.xsd
Source/Pawnmorphs/Esoteria/Aspects/Prideful.cs
Source/Pawnmorphs/Esoteria/PMTraitDefOf.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj

Added aspect to add and remove a new prideful trait that provides an increased risk of social fight. The trait as 0 commonality so it shouldn't occur normally.
Updated xsd and schemareference for aspects.

Morph balance prideful trait

---

Source/Pawnmorphs/Esoteria/User Interface/Dialog_PartPicker.cs

Issue 536 - Fixed trying to trigger comp update on pawns without comp.

---

Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs

Added recaching on injector hediffs after game reload since caches and state isn't saved.
closes #553

Issue 553 - Injectors not working after reload

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Added Doors Expanded door check method to mass patch if present.
closes #551

Issue 551 - Doors expanded blocks roamer morphs

---

1.3/Patches/IdeoPatches/PreceptPatches.xml

I am not able to actually verify that this works with ideology.
closes #530

Issue 530 - Updated patch to be conditional.

---

.github/workflows/Build_Test.yml
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj

Might want to squash before merging. Pipelines are always a lot of trial and error.
Finished pipeline run for Dev branch: https://github.com/Zeracronius/Pawnmorpher/actions/runs/2294789402

Semi-automatic compile action workflow

---

Source/Pawnmorphs/Esoteria/IncidentWorker/SheepChef.cs
Source/Pawnmorphs/Esoteria/IncidentWorker_ChaomorphPasses.cs
Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs

Issue #577 - Fixed Chao creatures spawning too young by incident.

---

Source/Pawnmorphs/Esoteria/TfSys/Mutagen.cs

If not normal flesh, then check if HAR species, and if so then check if it is Flesh compatible.
Closes #587

Issue 587 - Added HAR compatibility check for flesh type.

---

Source/Pawnmorphs/Esoteria/Aspect.cs
Source/Pawnmorphs/Esoteria/AspectTracker.cs
Source/Pawnmorphs/Esoteria/AspectUtils.cs
Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/HediffDefPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/StatWorkerPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/ThoughtUtilityPatches.cs
Source/Pawnmorphs/Esoteria/HediffComp_Production.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/Utilities/StatsUtility.cs
Source/Pawnmorphs/Esoteria/Utilities/TimedCache.cs

Added caching to various often called methods to hopefully improve overall performance.
Created TimedCache which updates cached value based on ticks since it was last updated, and ensures that it will only update once in the same tick regardless of how many times it is called.

Optimizations

---

Patches/Core/Core_HumanTailAdder.xml

Fixed condition check in tail patch.

Issue590 - Tail patch not working properly

---

Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/Need_Control.cs
Source/Pawnmorphs/Esoteria/ThingComps/SapienceTracker.cs

Simplified and added invalidation of intelligence cache.

---

Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/Hediffs/Hediff_MutagenicBase.cs
Source/Pawnmorphs/Esoteria/IngestionOutcomeDoer_CompleteTF.cs

Added additional checks to avoid warnings.
Closed 612

Issue #612 - Fixed feral pills not triggering full transformation.

---

Source/Pawnmorphs/Esoteria/ThingComps/SapienceTracker.cs

Issue 632 - Pawn is now undrafted if undraftable.

---

Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs

Issue 591 - Added check for sapiostore during full transformation.

---

Source/Pawnmorphs/Esoteria/HPatches/ThoughtHandlerPatches.cs

Issue 593 - Added check for sapience level when gaining ate without table.

---

Source/Pawnmorphs/Esoteria/TfSys/MergeMutagen.cs
Source/Pawnmorphs/Esoteria/TfSys/SimpleMechaniteMutagen.cs

This means that the implant will not transfer over nor impact the resulting form.
Closes #599

Issue 599 - Added null check to all Rest and food needs.

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Issue 627 - Added info card to mass patch.

---

Source/Pawnmorphs/Esoteria/Things/InjectorGenerator.cs

Issue 601 - Added check for no-injector in morphDef.

---

Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs

Issue 595 - Added check to stop perm-feral countdown

---

Source/Pawnmorphs/Esoteria/HPatches/PortraitCachePatches.cs

Patch is only called for former humans.
Closes #647

Issue 647 - Circumvented humanlike check in CurKindLifeStage.

---

Source/Pawnmorphs/Esoteria/HediffComp_Production.cs

Issue 644 - Moved stage calculation during load to after exposeData to ensure Pawn is available.

---

1.3/Defs/Things/Buildings.xml

Issue 651 - Enabled visible radius on mutagenic ship part when selected.

---

Source/Pawnmorphs/Esoteria/Graphics/GraphicsUpdaterComp.cs

Issue 654 - Added handling of transparent morph hairColorOverride

---

Source/Pawnmorphs/Esoteria/Graphics/InitialGraphics.cs
Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs

Support for races with different color channels.
Support for single-gender races.
Fixed hair not being updated.
Fixed crownType not being properly saved and loaded leading to missing heads.

Additional fixes for explicit race replacement support.

---

Languages/English/Keyed/Settings.xml
Source/Pawnmorphs/Esoteria/User Interface/Settings/Dialog_RaceReplacements.cs
Source/Pawnmorphs/Esoteria/User Interface/Settings/Dialog_VisibleRaceSelection.cs

Fixed issue where option lists didn't show all rows.

Hotfix for option lists

---

Source/Pawnmorphs/Esoteria/User Interface/FilterListBox.cs

Included rendering optimization from Wiki branch.

Fixed height calculations on listbox.

---

Source/Pawnmorphs/Esoteria/User Interface/Settings/Dialog_RaceReplacements.cs

Issue 676 - Added nullcheck on modContentPack info.

---

1.3/Defs/Pawnmorpher_Research.xml

Issue 666 - Adjusted reversion tech description

---

1.3/Defs/Morphs/Animal/Ungulate/EvenToedUngulate/Bovid/Bovid_MorphDef.xml

Issue 677 - Bovid herding

---

1.3/Patches/Core_HumanColorChannels.xml
1.3/Patches/Core_HumanHedifGraphics.xml
Source/Pawnmorphs/Esoteria/Hybrids/RaceGenerator.cs
Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs

Added custom colour channel that has skin colour as primary and hair colour as secondary.
This means that part colour mask would have skin as red and hair as green as assumed.

Fixed green colour mask not being hair color.

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Issue 671 - food restrictions

---

1.3/Defs/Thoughts/SapientAnimalThoughts/AspectRelated.xml
Source/Pawnmorphs/Esoteria/Thoughts/Worker_BeastMaster.cs

Updates an unused ThoughtWorker and applies to a bugged thought. Adjusts Thought description to avoid base game formatting limitations
closes #679 
closes #643

Fixed #679 and #643

---

Source/Pawnmorphs/Esoteria/TransformerUtility.cs

Issue 638 - Enabled equipment handling when transformed.

---

Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs

Sapient Former Humans now produce the same amount of filth as humans. Increased with Sapience Loss

Set FORMER_HUMAN_FILTH_ADJ to 1

---

Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
Source/Pawnmorphs/Esoteria/UserInterface/Dialog_PartPicker.cs

Cached alienrace component.
Added scaling by using meshes from alien component.
Prevented part picker from being available in chamber when containing a non-HAR race. Do we want to support part picker for non-HAR races? Can we even support mutations?

Added support for scaled pawns (and downscale) to part picker.

---

1.3/Mods/ZWE-ACP/Patches/zLoadLast_Addon_Leopard.xml

Hotfix for Animal Collab Project integration

Hotfix for Animal Collab Project integration

---

Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/PawnTransferUtilities.cs

I'm still new to Github, and I messed something up... Badly
closes #430

Transfer Abilities and Hediff Severity

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

closes #480 
Should work on all Modded ritual roles
If there is any Ritual still cancelled by a former human, then its jobs need to be checked manually.

Made(probably) all Vanilla Rituals and modded Ritual roles work

---

Patches/Mod Addons/Addon_FixZombieland.xml
Source/Pawnmorphs/Esoteria/BodyUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/PawnPatches.cs

closes #716
Probably
Too scared to test

Patch Zombies to be immune to all mutations

---

Languages/English/Keyed/UI_Genebank.xml
Source/Pawnmorphs/Esoteria/UserInterface/Genebank/GenebankTab.cs
Source/Pawnmorphs/Esoteria/UserInterface/Genebank/Tabs/AnimalsTab.cs
Source/Pawnmorphs/Esoteria/UserInterface/Genebank/Tabs/MutationsTab.cs
Source/Pawnmorphs/Esoteria/UserInterface/TableBox/Table.cs
Source/Pawnmorphs/Esoteria/UserInterface/TableBox/TableColumn.cs

Added animals and body parts columns and made mutations searchable by either.
Also added some hook methods to allow sub-mods to potentially add additional columns easily

Genebank UI tweaks

---

Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs

Issue 523 - Former ferals now get ideology equial to new faction pawn.

---

1.3/Defs/Hediffs/Hediffs_FormerHuman.xml
Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Issue 607 - Added extra methods to mass-patch

---

Source/Pawnmorphs/Esoteria/BodyUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/ApparelUtilityPatches.cs

Corrections to zombielands fix.

Zombielands

---

Languages/English/Keyed/Settings.xml
Source/Pawnmorphs/Esoteria/Hediffs/Composable/TFTypes.cs
Source/Pawnmorphs/Esoteria/Hybrids/RaceGenerator.cs
Source/Pawnmorphs/Esoteria/MorphDef.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
Source/Pawnmorphs/Esoteria/PawnmorpherSettings.cs
Source/Pawnmorphs/Esoteria/UserInterface/Dialog_Textbox.cs
Source/Pawnmorphs/Esoteria/UserInterface/FilterListBox.cs
Source/Pawnmorphs/Esoteria/UserInterface/Settings/Dialog_AnimalAssociations.cs
Source/Pawnmorphs/Esoteria/UserInterface/Settings/Dialog_RaceReplacements.cs

Added access to raw text value for configurations to allow import/export by copy-pasting.
Added options menu to associate animals to morphs to allow additional outcomes and more source for injector and mutations.

1.4 settings update

---

Source/Pawnmorphs/Esoteria/HPatches/PawnCompPatches.cs

A long-term solution would be to replace part of a the Postfix with a Transpiler, to replace the intelligence check with our sapience check. But this works for now

Fix adding needs to Children

---

Source/Pawnmorphs/Esoteria/HPatches/PawnCompPatches.cs
Source/Pawnmorphs/Esoteria/SapienceStates/FormerHuman.cs

Fix for mods checking genes on sapient pawns throwing exceptions on sapient former humans.

Issue 753 - former human genes exception

---

1.4/Defs/Drugs/Drugs_Injectors.xml
1.4/Defs/Races/Chaocreatures/Chaothrumbo.xml

Updated descriptions related to unstable genome to make it easier to figure out based on suggestion.
https://discord.com/channels/603713246461165578/1062954509971755161

Updated unstable genome related descriptions.

---

Source/Pawnmorphs/Esoteria/HPatches/PawnCapacityUtilsPatch.cs

Issue #750 - Replaced aspect capacity calculation with a hook injected into vanilla.

---

Source/Pawnmorphs/Esoteria/IncidentWorker/MutagenicLeak.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/SlurryNetDefOf.cs

Issue 775 - mutagenic leak

---

1.4/Defs/MainButtonDefs.xml
Languages/English/Keyed/UI_Genebank.xml
Languages/English/Keyed/UI_Localization.xml
Source/Pawnmorphs/Esoteria/PawnmorpherSettings.cs
Source/Pawnmorphs/Esoteria/UserInterface/FilterListBox.cs
Source/Pawnmorphs/Esoteria/UserInterface/MainTabWindow_ChamberDatabase.cs
Source/Pawnmorphs/Esoteria/UserInterface/TableBox/Table.cs
Source/Pawnmorphs/Esoteria/UserInterface/Window_Genebank.cs

An attempt at improving genebank to support high DPI and UI scaling as mentioned in #773
Removed a number of hardcoded pixel spacings making it more dynamic.
Added font selector to Genebank UI
Made genebank window store position and size to mod settings.
Added option to disable multiselect on Table control.
Closes #773

Genebank and Table UI improvements

---

Source/Pawnmorphs/Esoteria/UserInterface/Window_Genebank.cs

This would probably be better located when exiting the game, but I don't know where such an event might be located.

Genebank config is now saved when closed.

---

1.4/Defs/ThinkTrees/SapientAnimals.xml
1.4/Patches/Core/Core_AnimalThinkTree.xml
Source/Pawnmorphs/Esoteria/HPatches/PawnMindStatePatches.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Adds a new animalConstant think tree that conditionally branches into either vanilla animal constant or vanilla humanlike constant think trees.

Issue 608 - Fixed sapient animals fleeing in combat

---

Source/Pawnmorphs/Esoteria/AnimalClassDefOf.cs
Source/Pawnmorphs/Esoteria/MorphUtilities.cs

Issue 790 - chaomorph selection

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Refactored code to include code from other mods in mass-patching.
Solves #796

Issue 796 - blocking doors

---

Source/Pawnmorphs/Esoteria/Graphics/InitialGraphics.cs
Source/Pawnmorphs/Esoteria/Hediff_AddedMutation.cs
Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs

Issue 798 - Fixed women with muzzles causing errors on load.

---

Schemas/MorphDef.xsd
Source/Pawnmorphs/Esoteria/Graphics/InitialGraphics.cs
Source/Pawnmorphs/Esoteria/Hybrids/HybridRaceSettings.cs
Source/Pawnmorphs/Esoteria/Hybrids/RaceGenerator.cs
Source/Pawnmorphs/Esoteria/Hybrids/RaceShiftUtilities.cs

Added morph override option for lifeExpectancy, Body and baseHungerRate.
Morphs now pull blood and flesh type from associated animal.
MorphDefs can now have comps assigned.
Added XSD documentation to hybrid race settings.
Added morph hairstyles.

Expanded morphDef race settings

---

Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/PawnPatches.cs
Source/Pawnmorphs/Esoteria/Social/PMInteractionWeightsDef.cs
Source/Pawnmorphs/Esoteria/ThingComps/SapienceTracker.cs

Reduced garbage in PMInteractionWeightsDef
Added caching to FixGetAllDisabledWorkTypes
Flipped some comparisons to speed them up significantly.
Improved FixIsColonist prefix.

Some optimizations

---

Source/Pawnmorphs/Esoteria/Things/InjectorGenerator.cs

Fixed injectors showing up in storage filter under both Drugs and Drugs/Injectors

Issue 816 - injector filters

---

Source/Pawnmorphs/Esoteria/Social/PMInteractionWorkerBase.cs
Source/Pawnmorphs/Esoteria/Social/Worker_FormerHuman.cs

Added additional sanity checks to prevent self-interactions.

Issue 503 - Self-interaction

---

About/About.xml
Patches/Mod Addons/Addon_Hospitality.xml
Source/Pawnmorphs/Esoteria/Comp_MutaniteBed.cs
Source/Pawnmorphs/Esoteria/DebugUtils/DebugLogUtils.MutationLogging.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/Utilities/TimeMetrics.cs

Removed dependency on hugslib since it wasn't actually used.

Removed dependency on hugslib. (It wasn't actually used!)

---

Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
Source/Pawnmorphs/Esoteria/UserInterface/FilterTreeBox.cs
Source/Pawnmorphs/Esoteria/UserInterface/TreeBox/Listing_TreeFilter.cs
Source/Pawnmorphs/Esoteria/UserInterface/TreeBox/TreeNode_FilterBox.cs

Overhauled settings menu to include scroll bars.

Added filterable tree list box component.

---

Languages/English/Keyed/Chambers.xml
Languages/English/Keyed/Settings.xml
Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
Source/Pawnmorphs/Esoteria/UserInterface/FilterTreeBox.cs
Source/Pawnmorphs/Esoteria/UserInterface/TreeBox/Listing_TreeFilter.cs
Source/Pawnmorphs/Esoteria/UserInterface/TreeBox/TreeNode_FilterBox.cs

Converts the entire settings page into filterable tree list.

Settings update

---

Source/Pawnmorphs/Esoteria/HPatches/GamePatches.cs

Added null handling in narrow head fix patch.
Closes #819

Issue 819 - Narrow heads patch tweaks galore conflict.

---

Languages/English/Keyed/OptionalPatches.xml
Source/Pawnmorphs/Esoteria/HPatches/Optional/PawnScaling.cs
Source/Pawnmorphs/Esoteria/Interfaces/IConfigurableObject.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorpherMod.cs
Source/Pawnmorphs/Esoteria/PawnmorpherSettings.cs

Optional patches settings

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

Adds Pawn_PathFollow.TryEnterNExtPathCell and Building_Trap.KnowsOfTrap to the former human transpiler patches 
fixes #843

Former Humans now use humanlike pathfinding depending on sapience

---

Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs

added non sapient humanoids to colony animal list in MapPawns as well as adding the CompAssignableToPawns.DrawGUIOverlay 
fixes #808

added non sapient humanoids to colony animal list

---

Source/Pawnmorphs/Esoteria/AspectUtils.cs
Source/Pawnmorphs/Esoteria/BodyUtilities.cs
Source/Pawnmorphs/Esoteria/DebugUtils/PMDebugActions.cs
Source/Pawnmorphs/Esoteria/FormerHumanUtilities.cs
Source/Pawnmorphs/Esoteria/HPatches/PawnPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/ProductionCompPatches.cs
Source/Pawnmorphs/Esoteria/ITab_Pawn_Mutations.cs
Source/Pawnmorphs/Esoteria/MutationUtilities.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs
Source/Pawnmorphs/Esoteria/ThingComps/TFMilkable.cs
Source/Pawnmorphs/Esoteria/UserInterface/Dialog_BrowseGenebank.cs
Source/Pawnmorphs/Esoteria/UserInterface/Genebank/Tabs/AnimalsTab.cs
Source/Pawnmorphs/Esoteria/UserInterface/Genebank/Tabs/MutationsTab.cs
Source/Pawnmorphs/Esoteria/UserInterface/Genebank/Tabs/TemplatesTab.cs
Source/Pawnmorphs/Esoteria/UserInterface/TableBox/Table.cs
Source/Pawnmorphs/Esoteria/UserInterface/Window_Genebank.cs
Source/Pawnmorphs/Esoteria/Utilities/PatchUtilities.cs

Multiple optimizations using prepatcher
Replaced IsColonist patch with transpiler.

Additional prepatcher

---

1.4/Defs/MorphsAndMutationDefs/Animal/Avian/Anserigalliform/Anseriform/Chicken/Chicken_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Megafauna/ThickFur/Megasloth/Megasloth_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Megafauna/Thrumbo/Thrumbo_Hairstyle.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Megafauna/Thrumbo/Thrumbo_MorphDef.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Megafauna/Thrumbo/Thrumbo_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Familiaris/Husky/Husky_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Familiaris/Terrier/Terrier_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Lupine/Arctic Wolf/ArcticWolf_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Lupine/Timber Wolf/TimberWolf_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Scavenger/Hellhound/Hellhound_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/BigFelis/Cougar/Cougar_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/Pantherine/Panther/Panther_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Vulpine/Arctic Fox/ArcticFox_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Vulpine/Fennec Fox/FennecFox_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Vulpine/Red Fox/RedFox_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Reptile/Lacertilia/Iguana/Iguana_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Reptile/Ophidia/Cobra/Cobra_Hybrid.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Simian/Monkeys/Monkey/Monkey_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Bovid/DomesticatedBovid/Muffalo/Muffalo_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Cervid/SmallCervid/Deer/Deer_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Animal/Ungulate/OddToedUngulate/Equine/Horse/Horse_Parts.xml
1.4/Defs/MorphsAndMutationDefs/Shared/MiscMutations.xml
1.4/Defs/MorphsAndMutationDefs/Shared/SpineMutations.xml
1.4/Defs/StyleDefs/HairDefs.xml
Source/Pawnmorphs/Esoteria/Graphics/MutationStageGraphicsData.cs
Source/Pawnmorphs/Esoteria/Hediffs/MutationStage.cs
Source/Pawnmorphs/Esoteria/Hybrids/RaceGenerator.cs
Source/Pawnmorphs/Esoteria/Pawnmorph.csproj
Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs

Added support for HAR extended graphics which allows adding graphic filters directly in the graphic declerations.

Extended graphics support

---

Source/Pawnmorphs/Esoteria/Chambers/MutaChamber.cs
Source/Pawnmorphs/Esoteria/HPatches/FloatMenuMakerMapPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/GeneTrackerPatches.cs
Source/Pawnmorphs/Esoteria/HPatches/PawnPatches.cs
Source/Pawnmorphs/Esoteria/MorphUtilities.cs
Source/Pawnmorphs/Esoteria/PawnmorphPatches.cs
Source/Pawnmorphs/Esoteria/PawnmorpherModInit.cs
Source/Pawnmorphs/Esoteria/ThinkNodes/ConditionalOfFormerHuman.cs

Added initialisation profiling for debug builds.
Significantly optimised performance when right-clicking a downed pawn with another pawn.
Improved performance of gene skin colour patch.
Fixed issue related to missing ship part crash breaking settings menu.
Fixed missing associated animals breaking mod initialisation.

Polishing and fixes
